#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -e

# This is a multi-instance app, meaning it can be installed several times independently
# The id of the app as stated in the manifest is available as $YNH_APP_ID
# The instance number is available as $YNH_APP_INSTANCE_NUMBER (equals "1", "2", ...)
# The app instance name is available as $YNH_APP_INSTANCE_NAME
#    - the first time the app is installed, YNH_APP_INSTANCE_NAME = ynhexample
#    - the second time the app is installed, YNH_APP_INSTANCE_NAME = ynhexample__2
#    - ynhexample__{N} for the subsequent installations, with N=3,4, ...
# The app instance name is probably what you are interested the most, since this is
# guaranteed to be unique. This is a good unique identifier to define installation path,
# db names, ...
app=$YNH_APP_INSTANCE_NAME

# Retrieve arguments
domain=$YNH_APP_ARG_DOMAIN
path=$YNH_APP_ARG_PATH
is_public=$YNH_APP_ARG_IS_PUBLIC
language=$YNH_APP_ARG_LANGUAGE
src_path=/home/yunohost.app/$app
work_path=/home/yunohost.app/$app/githost
code_path=/home/yunohost.app/$app/gitsourcecode
# Source YunoHost helpers
source /usr/share/yunohost/helpers

# Save app settings
ynh_app_setting_set "$app" admin "$admin"
ynh_app_setting_set "$app" is_public "$is_public"
ynh_app_setting_set "$app" language "$language"

# Check domain/path availability
sudo yunohost app checkurl "${domain}${path}" -a "$app" \
    || ynh_die "Path not available: ${domain}${path}"


# Modify Nginx configuration file and copy it to Nginx conf directory
nginx_conf=../conf/nginx.conf
sed -i "s@YNH_WWW_PATH@$path@g" $nginx_conf
sed -i "s@YNH_WWW_ALIAS@$src_path/@g" $nginx_conf
sudo cp $nginx_conf /etc/nginx/conf.d/$domain.d/$app.conf


## create git repo and such 

sudo useradd -m -s /usr/bin/git-shell -d $src_path git
sudo mkdir -p $work_path
sudo mkdir -p $code_path
sudo git init --bare $code_path
sudo rm -v $code_path/hooks/*

## copy files over and make execuable 
cp -av ../sources/post-receive.sh /home/yunohost.app/$app/gitsourcecode/hooks/post-receive
sudo chmod +x /home/yunohost.app/$app/gitsourcecode/hooks/post-receive


## setup .ssh key and permissions for the folder
sudo mkdir -p $src_path/.ssh
sudo touch $src_path/.ssh/authorized_keys
echo -e $ssh_pubkey > authorized_keys
sudo cp authorized_keys $src_path/.ssh/
cd $src_path
sudo chmod 755 $src_path/.ssh
sudo chmod 644 $src_path/.ssh/authorized_keys
sudo chown git:git $src_path



## set up HTML
# sudo sed -i "s@ADDDOMAINNAME@$domain@g" index.html
# sudo sed -i "s@PATHNAME@$path@g" index.html
sudo cp index.html  /home/yunohost.app/$app/gitwebhost/


# If app is public, add url to SSOWat conf as skipped_uris
if [[ $is_public -eq 1 ]]; then
  # unprotected_uris allows SSO credentials to be passed anyway.
  ynh_app_setting_set "$app" unprotected_uris "/"
fi

# Reload services
sudo service nginx reload
